steps:
  - id: "Install packages"
    name: node:12.16.2
    entrypoint: yarn
    args: ['install']
  - id: "Build App"
    name: node:12.16.2
    entrypoint: yarn
    args: ['run', 'build']
  - id: "Deploy to Firebase"
    name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--only', 'hosting']